Adding support to Youyeetoo R1
Joshua-Riek/ubuntu-rockchip pull request #946
Opened 2024-07-26 13:47 UTC by SuperKali

Hi @Joshua-Riek,

I'm sending you this pull request to integrate the Youyeetoo R1. I want to emphasize, as always, that I'm still a beginner and hope to learn here. If you have any suggestions on how to best integrate this board, I'm available for testing since I own one.

From the vendor's SDK, I see a patch, but I think it is related to the fact that the partition table layout is based on Android rather than Linux. I'm not sure if it makes sense to integrate it here.

In any case, any advice or help from you is greatly appreciated.

Thank you.

2024-07-26 13:58 UTC, Joshua-Riek requested changes
It looks like the U-Boot device tree is missing. Do you have a link to the U-Boot source for this board? I can take a look.

As for the Android partition layout It's not needed.

2024-07-26 14:27 UTC, SuperKali commented
@Joshua-Riek i will upload the u-boot on my github soon

2024-07-26 14:33 UTC, SuperKali commented
@Joshua-Riek https://github.com/SuperKali/Youyeetoo-R1-U-Boot i just upload the uboot, soon i will upload the entire SDK...

2024-07-26 14:39 UTC, Joshua-Riek commented
I don't see the device tree for this board, is there no commit history for the SDK?

2024-07-26 14:42 UTC, SuperKali commented
> I don't see the device tree for this board, is there no commit history for the SDK?

I don't know, i just upload on github the u-boot directory from their SDK:
![image](https://github.com/user-attachments/assets/e471a3da-38d0-4c37-a8f5-dd950852fba6)

If you want, i can upload the entire directory.

2024-07-26 14:48 UTC, SuperKali commented
@Joshua-Riek i don't know if this can be useful:

![image](https://github.com/user-attachments/assets/0c10e934-56e3-45ec-b9b9-220e2390d0c7)

2024-07-26 14:55 UTC, Joshua-Riek commented
I can help make a basic device tree for U-Boot later today.

2024-07-26 15:00 UTC, SuperKali commented
@Joshua-Riek Thank you, i'm trying to upload the entire sdk, if it can be useful

2024-07-26 20:52 UTC, SuperKali commented
@Joshua-Riek unfortunately I can't upload the entire SDK on GitHub to a single repository... the size is 5.46gb and git only permit 2Gb...

I upload it on my own webhosting..
https://repo.superkali.me/yyt-r1/

2024-07-26 22:25 UTC, Joshua-Riek commented
Hey, can you apply this patch and see if the system boots?

```
From 1382927bf29b0a8631f845085fa4b5f1f8f1f056 Mon Sep 17 00:00:00 2001
From: Joshua Riek <jjriek@verizon.net>
Date: Fri, 26 Jul 2024 18:12:51 -0400
Subject: [PATCH] Add U-Boot support for Youyeetoo R1

---
 .../0014-Add-support-for-the-yyt-r1.patch     | 317 ++++++++++++++++++
 .../u-boot-radxa-rk3588/debian/patches/series |   2 +
 2 files changed, 319 insertions(+)
 create mode 100644 packages/u-boot-radxa-rk3588/debian/patches/0014-Add-support-for-the-yyt-r1.patch

diff --git a/packages/u-boot-radxa-rk3588/debian/patches/0014-Add-support-for-the-yyt-r1.patch b/packages/u-boot-radxa-rk3588/debian/patches/0014-Add-support-for-the-yyt-r1.patch
new file mode 100644
index 0000000..1fd2a64
--- /dev/null
+++ b/packages/u-boot-radxa-rk3588/debian/patches/0014-Add-support-for-the-yyt-r1.patch
@@ -0,0 +1,317 @@
+From b50423ff838b41f0419797991240b4347fe0d74e Mon Sep 17 00:00:00 2001
+From: Joshua Riek <jjriek@verizon.net>
+Date: Fri, 26 Jul 2024 18:11:07 -0400
+Subject: [PATCH] Add support for the yyt r1
+
+---
+ arch/arm/dts/rk3588s-youyeetoo-r1.dts  |  36 ++++
+ configs/youyeetoo-r1-rk3588s_defconfig | 254 +++++++++++++++++++++++++
+ 2 files changed, 290 insertions(+)
+ create mode 100644 arch/arm/dts/rk3588s-youyeetoo-r1.dts
+ create mode 100644 configs/youyeetoo-r1-rk3588s_defconfig
+
+diff --git a/arch/arm/dts/rk3588s-youyeetoo-r1.dts b/arch/arm/dts/rk3588s-youyeetoo-r1.dts
+new file mode 100644
+index 00000000000..e24b59d9d07
+--- /dev/null
++++ b/arch/arm/dts/rk3588s-youyeetoo-r1.dts
+@@ -0,0 +1,36 @@
++// SPDX-License-Identifier: (GPL-2.0+ OR MIT)
++/*
++ * Copyright (c) 2021 Rockchip Electronics Co., Ltd
++ *
++ */
++
++/dts-v1/;
++#include "rk3588.dtsi"
++#include "rk3588-u-boot.dtsi"
++#include <dt-bindings/input/input.h>
++
++/ {
++	model = "Youyeetoo R1";
++	compatible = "rockchip,rk3588s-youyeetoo-r1", "rockchip,rk3588";
++
++	vcc12v_dcin: vcc12v-dcin {
++		u-boot,dm-pre-reloc;
++		compatible = "regulator-fixed";
++		regulator-name = "vcc12v_dcin";
++		regulator-always-on;
++		regulator-boot-on;
++		regulator-min-microvolt = <12000000>;
++		regulator-max-microvolt = <12000000>;
++	};
++
++	vcc5v0_sys: vcc5v0-sys {
++		u-boot,dm-pre-reloc;
++		compatible = "regulator-fixed";
++		regulator-name = "vcc5v0_sys";
++		regulator-always-on;
++		regulator-boot-on;
++		regulator-min-microvolt = <5000000>;
++		regulator-max-microvolt = <5000000>;
++		vin-supply = <&vcc12v_dcin>;
++	};
++};
+diff --git a/configs/youyeetoo-r1-rk3588s_defconfig b/configs/youyeetoo-r1-rk3588s_defconfig
+new file mode 100644
+index 00000000000..44b2cf4067f
+--- /dev/null
++++ b/configs/youyeetoo-r1-rk3588s_defconfig
+@@ -0,0 +1,254 @@
++CONFIG_ARM=y
++CONFIG_ARM_CPU_SUSPEND=y
++CONFIG_ARCH_ROCKCHIP=y
++CONFIG_SPL_GPIO_SUPPORT=y
++CONFIG_SPL_LIBCOMMON_SUPPORT=y
++CONFIG_SPL_LIBGENERIC_SUPPORT=y
++CONFIG_SYS_MALLOC_F_LEN=0x80000
++CONFIG_SPL_FIT_GENERATOR="arch/arm/mach-rockchip/make_fit_atf.sh"
++CONFIG_ROCKCHIP_RK3588=y
++CONFIG_ROCKCHIP_USB_BOOT=y
++CONFIG_ROCKCHIP_FIT_IMAGE=y
++CONFIG_ROCKCHIP_HWID_DTB=y
++CONFIG_USING_KERNEL_DTB_V2=y
++CONFIG_ROCKCHIP_VENDOR_PARTITION=y
++CONFIG_ROCKCHIP_FIT_IMAGE_PACK=y
++CONFIG_ROCKCHIP_NEW_IDB=y
++CONFIG_LOADER_INI="RK3588MINIALL.ini"
++CONFIG_TRUST_INI="RK3588TRUST.ini"
++CONFIG_PSTORE=y
++CONFIG_SPL_SERIAL_SUPPORT=y
++CONFIG_SPL_DRIVERS_MISC_SUPPORT=y
++CONFIG_TARGET_EVB_RK3588=y
++CONFIG_SPL_LIBDISK_SUPPORT=y
++CONFIG_SPL_SPI_FLASH_SUPPORT=y
++CONFIG_SPL_SPI_SUPPORT=y
++CONFIG_DEFAULT_DEVICE_TREE="rk3588s-youyeetoo-r1"
++CONFIG_DEBUG_UART=y
++CONFIG_FIT=y
++CONFIG_FIT_IMAGE_POST_PROCESS=y
++CONFIG_FIT_HW_CRYPTO=y
++CONFIG_SPL_LOAD_FIT=y
++CONFIG_SPL_FIT_IMAGE_POST_PROCESS=y
++CONFIG_SPL_FIT_HW_CRYPTO=y
++# CONFIG_SPL_SYS_DCACHE_OFF is not set
++CONFIG_BOOTDELAY=0
++CONFIG_SYS_CONSOLE_INFO_QUIET=y
++# CONFIG_DISPLAY_CPUINFO is not set
++CONFIG_ANDROID_BOOTLOADER=y
++CONFIG_ANDROID_AVB=y
++CONFIG_ANDROID_BOOT_IMAGE_HASH=y
++CONFIG_SPL_BOARD_INIT=y
++# CONFIG_SPL_RAW_IMAGE_SUPPORT is not set
++# CONFIG_SPL_LEGACY_IMAGE_SUPPORT is not set
++CONFIG_SPL_SEPARATE_BSS=y
++CONFIG_SYS_MMCSD_RAW_MODE_U_BOOT_USE_PARTITION=y
++CONFIG_SYS_MMCSD_RAW_MODE_U_BOOT_PARTITION=0x1
++CONFIG_SPL_MMC_WRITE=y
++CONFIG_SPL_MTD_SUPPORT=y
++CONFIG_SPL_ATF=y
++CONFIG_FASTBOOT_BUF_ADDR=0xc00800
++CONFIG_FASTBOOT_BUF_SIZE=0x07000000
++CONFIG_FASTBOOT_FLASH=y
++CONFIG_FASTBOOT_FLASH_MMC_DEV=0
++CONFIG_CMD_BOOTZ=y
++CONFIG_CMD_DTIMG=y
++# CONFIG_CMD_ELF is not set
++# CONFIG_CMD_IMI is not set
++# CONFIG_CMD_IMLS is not set
++# CONFIG_CMD_XIMG is not set
++# CONFIG_CMD_LZMADEC is not set
++# CONFIG_CMD_UNZIP is not set
++# CONFIG_CMD_FLASH is not set
++# CONFIG_CMD_FPGA is not set
++CONFIG_CMD_GPT=y
++# CONFIG_CMD_LOADB is not set
++# CONFIG_CMD_LOADS is not set
++CONFIG_CMD_BOOT_ANDROID=y
++CONFIG_CMD_MMC=y
++CONFIG_CMD_PCI=y
++CONFIG_CMD_SF=y
++CONFIG_CMD_SPI=y
++CONFIG_CMD_USB=y
++CONFIG_CMD_USB_MASS_STORAGE=y
++# CONFIG_CMD_ITEST is not set
++# CONFIG_CMD_SETEXPR is not set
++CONFIG_CMD_TFTPPUT=y
++CONFIG_CMD_TFTP_BOOTM=y
++CONFIG_CMD_TFTP_FLASH=y
++# CONFIG_CMD_MISC is not set
++CONFIG_CMD_MTD_BLK=y
++# CONFIG_SPL_DOS_PARTITION is not set
++# CONFIG_ISO_PARTITION is not set
++CONFIG_EFI_PARTITION_ENTRIES_NUMBERS=64
++CONFIG_SPL_OF_CONTROL=y
++CONFIG_SPL_DTB_MINIMUM=y
++CONFIG_OF_LIVE=y
++CONFIG_OF_SPL_REMOVE_PROPS="clock-names interrupt-parent assigned-clocks assigned-clock-rates assigned-clock-parents"
++# CONFIG_NET_TFTP_VARS is not set
++CONFIG_REGMAP=y
++CONFIG_SPL_REGMAP=y
++CONFIG_SYSCON=y
++CONFIG_SPL_SYSCON=y
++# CONFIG_SARADC_ROCKCHIP is not set
++CONFIG_SARADC_ROCKCHIP_V2=y
++CONFIG_CLK=y
++CONFIG_SPL_CLK=y
++CONFIG_CLK_SCMI=y
++CONFIG_SPL_CLK_SCMI=y
++CONFIG_DM_CRYPTO=y
++CONFIG_SPL_DM_CRYPTO=y
++CONFIG_ROCKCHIP_CRYPTO_V2=y
++CONFIG_SPL_ROCKCHIP_CRYPTO_V2=y
++CONFIG_DM_RNG=y
++CONFIG_RNG_ROCKCHIP=y
++CONFIG_SCMI_FIRMWARE=y
++CONFIG_SPL_SCMI_FIRMWARE=y
++CONFIG_GPIO_HOG=y
++CONFIG_ROCKCHIP_GPIO=y
++CONFIG_ROCKCHIP_GPIO_V2=y
++CONFIG_SYS_I2C_ROCKCHIP=y
++CONFIG_I2C_MUX=y
++CONFIG_DM_KEY=y
++CONFIG_RK8XX_PWRKEY=y
++CONFIG_ADC_KEY=y
++CONFIG_MISC=y
++CONFIG_SPL_MISC=y
++CONFIG_MISC_DECOMPRESS=y
++CONFIG_SPL_MISC_DECOMPRESS=y
++CONFIG_ROCKCHIP_OTP=y
++CONFIG_ROCKCHIP_HW_DECOMPRESS=y
++CONFIG_SPL_ROCKCHIP_HW_DECOMPRESS=y
++CONFIG_SPL_ROCKCHIP_SECURE_OTP=y
++CONFIG_MMC_DW=y
++CONFIG_MMC_DW_ROCKCHIP=y
++CONFIG_MMC_SDHCI=y
++CONFIG_MMC_SDHCI_SDMA=y
++CONFIG_MMC_SDHCI_ROCKCHIP=y
++CONFIG_MTD=y
++CONFIG_MTD_BLK=y
++CONFIG_MTD_DEVICE=y
++CONFIG_NAND=y
++CONFIG_MTD_SPI_NAND=y
++CONFIG_SPI_FLASH=y
++CONFIG_SF_DEFAULT_SPEED=80000000
++CONFIG_SPI_FLASH_EON=y
++CONFIG_SPI_FLASH_GIGADEVICE=y
++CONFIG_SPI_FLASH_MACRONIX=y
++CONFIG_SPI_FLASH_SST=y
++CONFIG_SPI_FLASH_WINBOND=y
++CONFIG_SPI_FLASH_XMC=y
++CONFIG_SPI_FLASH_XTX=y
++CONFIG_SPI_FLASH_MTD=y
++CONFIG_DM_ETH=y
++CONFIG_DM_ETH_PHY=y
++CONFIG_DWC_ETH_QOS=y
++CONFIG_GMAC_ROCKCHIP=y
++CONFIG_NVME=y
++CONFIG_PCI=y
++CONFIG_DM_PCI=y
++CONFIG_DM_PCI_COMPAT=y
++CONFIG_PCIE_DW_ROCKCHIP=y
++CONFIG_PHY_ROCKCHIP_INNO_USB2=y
++CONFIG_PHY_ROCKCHIP_NANENG_COMBOPHY=y
++CONFIG_PHY_ROCKCHIP_SAMSUNG_HDPTX=y
++CONFIG_PHY_ROCKCHIP_USBDP=y
++CONFIG_PINCTRL=y
++CONFIG_SPL_PINCTRL=y
++CONFIG_DM_FUEL_GAUGE=y
++CONFIG_POWER_FG_CW201X=y
++CONFIG_POWER_FG_CW221X=y
++CONFIG_DM_PMIC=y
++CONFIG_PMIC_SPI_RK8XX=y
++CONFIG_DM_POWER_DELIVERY=y
++CONFIG_TYPEC_TCPM=y
++CONFIG_TYPEC_TCPCI=y
++CONFIG_TYPEC_HUSB311=y
++CONFIG_TYPEC_FUSB302=y
++CONFIG_REGULATOR_PWM=y
++CONFIG_DM_REGULATOR_FIXED=y
++CONFIG_DM_REGULATOR_GPIO=y
++CONFIG_REGULATOR_RK860X=y
++CONFIG_REGULATOR_RK806=y
++CONFIG_CHARGER_BQ25700=y
++CONFIG_CHARGER_BQ25890=y
++CONFIG_CHARGER_SC8551=y
++CONFIG_CHARGER_SGM41542=y
++CONFIG_DM_CHARGE_DISPLAY=y
++CONFIG_CHARGE_ANIMATION=y
++CONFIG_PWM_ROCKCHIP=y
++CONFIG_RAM=y
++CONFIG_SPL_RAM=y
++CONFIG_TPL_RAM=y
++CONFIG_ROCKCHIP_SDRAM_COMMON=y
++CONFIG_ROCKCHIP_TPL_INIT_DRAM_TYPE=0
++CONFIG_DM_RESET=y
++CONFIG_SPL_DM_RESET=y
++CONFIG_SPL_RESET_ROCKCHIP=y
++CONFIG_BAUDRATE=1500000
++CON [...]

2024-07-26 23:09 UTC, Joshua-Riek commented
I need to say, whoever at Youyeetoo made the device tree, did a terrible job. Iv'e seen a lot of bad RK3588 device trees, this is by far the worst. If anyone from Youyeetoo sees this PR, screw you lol.

2024-07-27 07:19 UTC, SuperKali commented
@Joshua-Riek i got this error on compilation:

root@asd:~/ubuntu-rockchip# ./build.sh -b youyeetoo-r1 -s noble -f server
mv: cannot stat 'rootfs/etc/resolv.conf': No such file or directory
Error: in ./scripts/config-image.sh on line 95
Error: in ./build.sh on line 223

i'm using ubuntu 20.04

2024-07-27 12:35 UTC, SuperKali commented
[build-20240727114005.log](https://github.com/user-attachments/files/16400203/build-20240727114005.log)
@Joshua-Riek here the log attached.

2024-07-27 15:53 UTC, SuperKali commented
@Joshua-Riek i compiled the OS but unfortunately it didn't boot correctly:

```bash
U-Boot 2017.09 (Jul 27 2024 - 13:51:42 +0000)

Model: Youy0x81000000
PreSerial: 2, raw, 0xfeb50000
DRAM:  8 GiB
Sysmem: init
Relocation Offset: eda0e000
Relocation fdtCR: M/C/I
Using default environment

DM: v2
no mmc device at slot 1
mmc@fe2c0000: 1 (SD), mmc@fe2e0000: 0
Bootdev(atags): mmc 1
MMC1: Legacy, 52Mhz
PartType: EFINo misc partition
boot mode: None
FIT: No boot partition
Failed to load DTB, ret=-2
No valid DTB, ret=-22
Failed to get kernel dtb, ret=-22
Model: YouIDR: 0x81000000
CLK: (sync kernel. arm: enter 1008000 KHz, init 1008000 KHz, kernel 0N/A)
  b0pll 24000 KHz
  b1pll 24000 KHz
  lpll 24000 KHz
  v0pll 24000 KHz
  aupll 241188000 KHz
  npll 24000 KHz
  ppll 1100000 KHz
  aclk_center_root 702000 KHz
  pclk_center_96000 KHz
  aclk_center_low_root 500000 KHz
  aclk_top_root 750000 KHz
  pclk_top_root 100000No misc partition
Net:   No ethernet found.
Hit key to stop autoboot('CTRL+C') 0 
starting USB...
No working controllers found
USB is stopped. Please issue 'usb start' .
switch to partitions #0, OK
mmc1 is current device
Scanning mmc 1:2...
Found /boot/extlinux/extlinux.conf
Retrieving file: /boot/extlinux/extlinux.conf
979 bytes read in 16 ms (59.6 KiB/s)
U-Boot menu
1:	Ubuntu 24.04 LTS 6.1.0-1020-rockchip
2:	Ucue target)
Enter choice: 1:	Ubuntu 24.04 LTS 6.1.0-1020-rockchip
Retrieving file: /boot/6.1.0-1020-rockchip
15890071 bytes read in 1293 ms (11.7 MiB/s)
41032192 bytes read in 3319 ms (11.8 MiB/s)ockchip
append: root=UUID=160d9419-76f9-4d16-8574-a8da480eacf8 rootwait rw console=ttyS2,1500000 console=tty1 cgroup_enablele=memory
Retrieving file: /lib/firmware/6.1.0-1020-rockchip/device-tree/rockchip/rk3588s-youye251182 bytes read in 350 ms (700.2 KiB/s)
Fdt Ramdisk skip relocation
No misc partition
## Flattened Device Tree blob at 0x08300000
   Booting using the fdt blob at   Using Device Tree in place at 0000000008300000, end 000000000834052d
WARNING: could not set reg FDT_ERR_BADOFFSET.
## reserved-memory:
  ramoops@110000: addr=110000 size=e0000
Ax00200000 - 0xf0000000 (size: 0xefe00000)
Adding bank: 0x100000000 - 0x200000000 (size: 0x1000000000000 (size: 0x10000000)
Total: 9667.724/10393.161 ms

Starting kernel ...

[   10.405456] Booting Linux on physical CPU 0x0000000000 [0x412fd050]
[   10.405489] Linux ver.1.0-1020-rockchip (root@asd) (aarch64-linux-gnu-gcc (Ubuntu 11.u1~22.04) 11.4.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #20 SMP Sat Jul 27 13:45:36 UTC 2024
[yeetoo R1
[   10.415695] earlycon: uart8250 at MMIO32 0x00000000feb50000 (options '')
[   10.48250] enabled
[   10.422314] efi: UEFI not found.
[   10.425718] OF: fdt: Reserved memory: failed to reserve memory for node 'drm-logo@0': base 0x00000000000, size 0 MiB
[   10.426720] OF: fdt: Reserved memoryd to reserve memory for node 'drm-cubic-lut@0': base 0x0000000000000000, size 0 MiB
[   10.4278reated CMA memory pool at 0x00000002ff800000, size 8 MiB
[   10.428535] OF: reserved mem: initihared-dma-pool
[   10.579832] Zone ranges:
[   10.580078]   DMA      [mem 0x00000ffffffff]
[   10.580647]   DMA32    empty
[   10.580913]     [mem 0x0000000100000000-0x00000002ffffffff]
[   10.581477] Movable zone start for each node
 ranges
[   10.582183]   node   0: [mem 0x0000000000200000-0x00000000efffffff]
[   10.582752] 00000-0x00000001ffffffff]
[   10.583321]   node   0: [mem 0x00000002f0000000-0x00000002ffffffffp node 0 [mem 0x0000000000200000-0x00000002ffffffff]
[   10.605211] On node 0, zone DMA: 512 pages in unavailable ran8] psci: probing for conduit method from DT.
[   10.629913] pscv1.1 detected in firmware.
[   10.630333] psci: Using standard PSCI v0.2 function IDs
[   10.6ot supported.
[   10.631279] psci: SMC Calling Convention v1.2
[   10.632088] percpu: Embedded 29 pages/cpu s80504 r8192 d30088 u118784
[   10.632873] Detectcache on CPU0
[   10.633296] CPU features: detected: GIC system register CPU interface
[   10.etected: Virtualization Host Extensions
[   10.634449] CPU features: detected: Qualcomm erratum 2441009
[   10.635195] CPU features: detected: ARM errata 1165522, 1319367, or 1530923
[   10boot alternatives
[   10.636675] Built 1 zonelists, mobility gr Total pages: 2063880
[   10.637304] Kernel command line: root=PARTUUID=614e0000-0000 rootwait  cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory earlycon=uart8250,mmio32,0xfeb50000 i.rcu_expedited=1 rcu_nocbs=all androidboot.fwver=bl31-v1.45,uboot-07/27/2024
[   10.640189] Unknown kernel command line parameters "cgroup_enable=memory cgroupsed to user space.
[   10.642084] Dentry cache hash table entrider: 11, 8388608 bytes, linear)
[   10.643209] Inode-cache hash table entries: 524288 (order: 10, 4194304 bytes, linear)
[   1nit: stack:off, heap alloc:off, heap free:off
[   10.644491] software IO TLB: area num 8.
[   10.657559] software IO TLB: mapped [mem 0x00000000ec000000-000f0000000] (64MB)
[   10.761768] Memory: 8093440K/8386560K available (18816K kernel code, 3910K rwdata, 9248K roda7936K init, 779K bss, 284928K reserved, 8192K cma-reserved)
[   10.763220] SLUB: HWalign=64, Or MinObjects=0, CPUs=8, Nodes=1
[   10.763863] ftrace: allocatin75937 entries in 297 pages
[   10.916110] ftrace: allocated 297 pages with 4 groups
[   10.916700] trace event string veri[   10.917368] rcu: Hierarchical RCU implementation.
[   10.917ed.
[   10.918208] 	All grace periods are expedited (rcu_expedited).
[   10.918727] 	Rude vari  10.919141] 	Tracing variant of Tasks RCU enabled.
[   10.919573] rcu: RCU calculated value of jiffies.
[   10.930184] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
[   10.933785] GICv3: GIC: Using split EOI/Deactivate mode
[   10.934259] GICv3: 480 SPIs imple
                                    [   10.934607] GICv3: 0 Extended SPIs implemented
[   10.935055] Root IRQ handler: gic_handle_irq
[   10.935459] GICv3: GICv3 features: 16 PPIs
[   10.93586istributor 0 region 0:0x00000000fe680000
[   10.936868] ITS [mem 0xfe640000-0xfe65ffff]
[   10.937299] ITS@0x00000000fe640000: allocated 8192 Devices @100250000 (indirect, esz 8, psz 64K, sh[   10.938173] ITS@0x00000000fe68 Interrupt Collections @100260000 (flat, esz 2, psz 64K, shr 0).939117] ITS: using cache flushing for cmd queue
[   10.939601] ITS [mem 0xfe660000-0xfe67ffff]S@0x00000000fe660000: allocated 8192 Devices @100280000 (indirect, esz 8, psz 64K, shr 0)
[   1000: allocated 32768 Interrupt Collections @100290000 (flat, esz 2, psz 64K, shr 0)
[   10.9418or cmd queue
[   10.942501] GICv3: using LPI property table @0x[   10.943167] GIC: using cache flushing for LPI property table
[   10.943682] GICv3: CPU0: usi@0x00000001002b0000
[   10.944396] rcu: srcu_init: Setting srcu_struct sizes based on contentio[   11.080499] arch_timer: cp15 timer(s) running at 24.00MHz (ph clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x588fe9dc0, max_idle_ns: 440ched_clock: 56 bits at 24MHz, resolution 41ns, wraps every 4398046511097ns
[   11.084253] Console: colour dummy device 80x25
[   11.084673] printk: console [tprintk: bootconsole [uart8250] disabled
[   10.405456] Booting Linux on physical CPU 0x0000000000 [0x412]
[   10.405489] Linux version 6.1.0-1020-rockchip (root@asd) (aarch64-linux-gnu-gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, GNU ld (ils for Ubuntu) 2.38) #20 SMP Sat Jul 27 13:45:36 UTC 2024
[   10.415583] Machine model: Youyee8250 at MMIO32 0x00000000feb50000 (options '')
[   10.418770] printk: bootconsole [uart8250] enound.
[   10.425718] OF: fdt: Reserved memory: failed to reserve memory for node 'drm-logo@0':    10.426720] OF: fdt: Reserved memory: failed to reserve memory for node 'drm-cubic-lut@0': bas 10.427817] Reserved memory: created CMA memory pool at 0x00000002ff800000, size 8 MiB
[   10.4ode cma, compatible id shared-dma-pool
[   10.579832] Zone ranges:
[   10.580078]   DMA      [ffff]
[   10.580647]   DMA32    empty
[   10.580913]   Normal   [mem 0x0000000100000000-0x0000 zone start for each node
[   10.581861] Early [...]

2024-07-27 16:19 UTC, Joshua-Riek commented
The goodix device tree binding is not setup correctly, but i found a typo https://github.com/Joshua-Riek/linux-rockchip/commit/3029616317850a58dfd4f4afa1ced6003a892da7 that should fix the problem.

2024-07-27 16:22 UTC, SuperKali commented
> The goodix device tree binding is not setup correctly, but i found a typo [Joshua-Riek/linux-rockchip@3029616](https://github.com/Joshua-Riek/linux-rockchip/commit/3029616317850a58dfd4f4afa1ced6003a892da7) that should fix the problem.

Ok, I sync my repo, and will rebuild the OS.

I always thank you for your patience and help.

2024-07-27 16:27 UTC, SuperKali commented
I started the workflow.

I need to wait again 😂

https://github.com/SuperKali/ubuntu-rockchip/actions/runs/10124906781

2024-07-27 16:51 UTC, Joshua-Riek commented
When GitHub adds arm64 runners it should be much faster, but i have no idea when they will add them.

2024-07-27 16:59 UTC, SuperKali commented
> When GitHub adds arm64 runners it should be much faster, but i have no idea when they will add them.

Next time I will add my own worker 😂 surely is more faster than it

2024-07-27 20:14 UTC, SuperKali commented
@Joshua-Riek after recompiled the SO, I got the same issue, system stuck on boot:
<img width="1800" alt="image" src="https://github.com/user-attachments/assets/57bf68fd-404e-4c45-8585-bc4e06fadc37">

2024-07-27 20:52 UTC, SuperKali commented
+ @ yytCharles

2024-07-27 21:00 UTC, SuperKali commented
@Joshua-Riek https://github.com/youyeetoo/r1-linux-kernel.5.10/blob/master/arch/arm64/boot/dts/rockchip/rk3588s-yyt.dump.dts idk but this "dump" is called?

2024-07-27 23:08 UTC, SuperKali commented
@Joshua-Riek why you’ve removed from the kernel the dts?

2024-07-27 23:14 UTC, Joshua-Riek commented
@SuperKali I dropped the kernel commits made for this board. I really need to start enforcing a higher code quality standard as I will be the one maintaining the kernel, I honestly should never have accepted the pull request as its both terrible code and does not even work. I'm sorry for inconvenience, your welcome to submit another pull request with cleaned up code.

2024-07-27 23:22 UTC, SuperKali commented
@Joshua-Riek I really need a help because I never wrote dts file, I don't understand how use that.
For this I need your help to integrate this board on your project

2024-07-28 00:02 UTC, Joshua-Riek commented
> @Joshua-Riek I really need a help because I never wrote dts file, I don't understand how use that. For this I need your help to integrate this board on your project

I originally accepted the kernel pull request due to this factor, but I'm sorry, I must be firm in this matter. I have so many boards and really can't deal with this. Again I understand where your coming from, It took me a long time to learn how to make a device tree and how the kernel works. If you wish to submit this again you need to invest time into learning more about device trees, or hope that someone who is not a complete idiot at youyeetoo will create a proper device tree for the R1.

I've dealt with a lot of crap from hardware vendors with their poor device trees and drivers. The amount of work I do for these vendors for free is insane, so I'm done doing things and helping in areas where I have no desire.

2024-07-28 14:31 UTC, SuperKali commented
@Joshua-Riek i tried to boot the nanopi r6c image on the youyeetoo r1 with jammy os...

![image](https://github.com/user-attachments/assets/c6014336-299e-40ef-a53b-2a27fe3f3c5b)

Works great! We can adapt the same DTS file?

2024-07-28 14:33 UTC, SuperKali commented
this is the dmesg
[10 476572 Booting Linux.txt](https://github.com/user-attachments/files/16404078/10.476572.Booting.Linux.txt)

2024-07-28 14:38 UTC, SuperKali commented
i checked the Wi-Fi module:
![image](https://github.com/user-attachments/assets/2ba993f0-a4f3-42a2-afca-6d9e0c51e339)
it works without any issues.

2024-07-28 14:55 UTC, SuperKali commented
I tried also to boot the image nooble of nano pi r6c and work too but there are some errors:
[nooble-kernel6.x.txt](https://github.com/user-attachments/files/16404137/nooble-kernel6.x.txt)

2024-07-28 21:06 UTC, Joshua-Riek commented
Using the device tree from another board is not a valid solution to this problem.

2024-07-28 21:14 UTC, SuperKali commented
@Joshua-Riek I understand that it is not valid, but already it works starting from that DTS with development you can integrate/remove things that you need or don't need for that board, then if you don't feel like regardless....

2024-07-28 21:19 UTC, Joshua-Riek commented
I'm closing this pull request. 

Do not bother me again unless you have valid code as I have previously stated.

2024-07-28 21:19 UTC, closed without merging